- name: Ensure systemd default target dir exists for user
  file:
    dest: /home/{{ username }}/.config/systemd/user/default.target.wants/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Enable notification service
  systemd:
    name: dunst
    scope: user
    enabled: yes
    state: restarted
  become: yes
  become_user: "{{ username }}"
  tags:
    - systemd
